### ISSUE TITLE
extra ent import 数据库结构导出到 schema 报错 panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by gufei** [suyuan32/goctls#118]
goctls 1.7.15

`$ goctls extra ent import -d "mysql://simple-admin:simple-admin.@tcp(localhost:3306)/test?charset=utf8mb4&parseTime=True&loc=Local" -t "batch_msg"
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/suyuan32/goctls/extra/ent/importschema.removeOldAnnotation({0xc0000e9800, 0x78d}, {0xc0000e9835?, 0x20?})
        C:/Users/USER/go/pkg/mod/github.com/suyuan32/goctls@v1.7.15/extra/ent/importschema/format.go:83 +0x11a
github.com/suyuan32/goctls/extra/ent/importschema.FormatFile(0xc00277db88)
        C:/Users/USER/go/pkg/mod/github.com/suyuan32/goctls@v1.7.15/extra/ent/importschema/format.go:46 +0x356
github.com/suyuan32/goctls/extra/ent/importschema.Gen(0xc0002d3b00?, {0xe69f9d?, 0x4?, 0xe69fa1?})
        C:/Users/USER/go/pkg/mod/github.com/suyuan32/goctls@v1.7.15/extra/ent/importschema/gen.go:122 +0x710
github.com/spf13/cobra.(*Command).execute(0xc0001b1808, {0xc000598140, 0x4, 0x4})
        C:/Users/USER/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc000163508)
        C:/Users/USER/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/USER/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/suyuan32/goctls/cmd.Execute()
        C:/Users/USER/go/pkg/mod/github.com/suyuan32/goctls@v1.7.15/cmd/root.go:49 +0x6c
main.main()
        C:/Users/USER/go/pkg/mod/github.com/suyuan32/goctls@v1.7.15/goctls.go:12 +0x48`

**Comment by gufei** [comment]
通过检查，发现在以往的schema文件中
有一个文件是如下内容
`
import (
	"wechat-api/ent/custom_types"
	"wechat-api/ent/schema/localmixin"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/suyuan32/simple-admin-common/orm/ent/mixins"
)

type SopNode struct {
	ent.Schema
}
`

github.com\suyuan32\goctls@v1.7.15\extra\ent\importschema\format.go 中的 getSchemaName 方法，是按type这个关键字进行查询的，由于这个内容中有一个 "wechat-api/ent/custom_types" 造成查询的 getSchemaName 不对，所以产生的异常

**Comment by suyuan32** [comment]
嗯，可以修复下

**Comment by suyuan32** [comment]
已修复
