### ISSUE TITLE
生成go代码时报错

### ISSUE THREAD

**Issue by maple-j** [suyuan32/goctls#19]
按教程走报错
`syntax error: all.api 1:1 expected syntax statement, got <*ast.ImportLiteralStmt>`

在每个api文件加上syntax = "v1"后报错` import circle not allowed`

**Comment by maple-j** [comment]
❯ goctls -v
goctls version v1.6.0 linux/amd64 - Go Zero v1.5.5 - Simple Admin Tools v1.5.16

**Comment by suyuan32** [comment]
circle not allowed 指的是你的 api 文件里面存在循环引用，检查下 import

**Comment by maple-j** [comment]
> circle not allowed 指的是你的 api 文件里面存在循环引用，检查下 import

问题就是我发现没循环引用😂
使用goctls api go --api ./desc/all.api --dir ./ --trans_err=true --style=go_zero 时提示不能循环引用
使用goctls api go --api ./desc/user/user.api --dir ./ --trans_err=true --style=go_zero 可以生成

desc/all.api:
```
syntax = "v1"

import "base.api"
import "user/user.api"

```
desc/base.api和example中一致

desc/user/user.api:
```
syntax = "v1"

import "../base.api"

type (
  ...
)
```

**Comment by maple-j** [comment]
包括我直接clone github.com/suyuan32/simple-admin-example-api 示例,也是一样的情况

**Comment by suyuan32** [comment]
你是什么系统？

**Comment by maple-j** [comment]
> 你是什么系统？

❯ uname -a
Linux user-manjaro 6.1.49-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Aug 27 23:08:04 UTC 2023 x86_64 GNU/Linux

**Comment by suyuan32** [comment]
go install github.com/suyuan32/goctls@fecaf05

**Comment by suyuan32** [comment]
执行上面的命令安装再试试

**Comment by suyuan32** [comment]
![image](https://github.com/suyuan32/goctls/assets/21239039/83709e89-bb00-4213-9c28-a5e071c4b845)

我给 file 项目执行 make gen-api 是可以的

**Comment by maple-j** [comment]
我在示例上跑依然是`syntax error: teacher.api 3:8 import circle not allowed`😂

**Comment by suyuan32** [comment]
![image](https://github.com/suyuan32/goctls/assets/21239039/96cbe16a-e1ca-45b9-888d-582b3f76a060)

**Comment by suyuan32** [comment]
啥都没改在示例运行没问题

**Comment by maple-j** [comment]
> 

我要在实例的api文件上加一行`syntax = "v1"`才能继续执行

**Comment by suyuan32** [comment]
你是不是之前用goctl生成了本地模板啥的

**Comment by maple-j** [comment]
> 你是不是之前用goctl生成了本地模板啥的

是的

**Comment by suyuan32** [comment]
估计是模板冲突了，清理本地模板可能就可以了

**Comment by suyuan32** [comment]
goctls template clean

**Comment by maple-j** [comment]
> goctls template clean

成了😂

**Comment by maple-j** [comment]
> goctls template clean

我把.goctl/env删掉就ok了

**Comment by suyuan32** [comment]
好吧，我看看是啥导致的

**Comment by maple-j** [comment]
> 好吧，我看看是啥导致的

是env文件下的GOCTL_EXPERIMENTAL这个变量改成False就可以了

**Comment by suyuan32** [comment]
ok

**Comment by maple-j** [comment]
🥰加油,希望做得越来越好
