### ISSUE TITLE
关于新建API时的一些建议

### ISSUE THREAD

**Issue by Gowa2017** [suyuan32/goctls#40]
1. 当使用 `goctls api new -e proj` 时，会生成 ent 目录下 Model 是 proj 的相关内容，实际上这可能并不符合实际的情况，项目名并不一定就和模型名或表名。因此默认应该只提供基础的支持，不生成默认的一个schema及相关代码。
2. 使用  `goctls api ent ` 使用时，命令行显示可以不需要指定 -m 模型以生成所有的内容。当当前必须这样使用
```sh
 goctls api  ent -c ./ent/schema -a sync --model ' '
```
有点不符合直觉

**Comment by suyuan32** [comment]
生成时会覆盖，你不可能一次定义所有 model 的，后期不好维护，只有第一次导入可能才用到，不过 group 又不灵活了

**Comment by suyuan32** [comment]
v1.6.12 model=all 生成所有schema
