### ISSUE TITLE
ent模板set_not_nil，JSON类型判断nil

### ISSUE THREAD

**Issue by DaWei-GeGe** [suyuan32/goctls#88]
JSON类型需要使用len(*value) > 0 判断是否为nil
`{{/* gotype: entgo.io/ent/entc/gen.Graph */}}

{{ define "set_not_nil" }}

    {{/* Add the base header for the generated file */}}
    {{ $pkg := base $.Config.Package }}
    {{ template "header" $ }}

    {{/* Loop over all updaters and implement the "SetNotNil" method for all optional fields */}}
    {{ range $n := $.Nodes }}
        {{ range $f := $n.MutableFields }}
            {{ $set := print "Set" $f.StructField }}

            {{ range $updater := list $n.UpdateName $n.UpdateOneName $n.CreateName}}
                // set field if value's pointer is not nil.
                func ({{ $n.Receiver }} *{{ $updater }}) SetNotNil{{ $f.StructField }}(value *{{ $f.Type }}) *{{ $updater }} {
                {{ if $f.IsJSON }}
                if len(*value) > 0 {
                {{ else }}
                if value != nil  {
                {{ end }}
                return {{ $n.Receiver }}.{{ $set }}(*value)
                }
                return {{ $n.Receiver }}
                }
            {{ end }}
        {{ end }}
    {{ end }}
{{ end }}`

**Comment by suyuan32** [comment]
Json 如果是结构体就会有 Bug 吧，你这只适合切片的情况

**Comment by DaWei-GeGe** [comment]
`field.JSON("images", []string{})`
确实还需要修改其它几个地方
```
1、api：Images  []string `json:"images,optional"`
2、logic：SetNotNilImages(&req.Images)
```
这样有个好处就是前端批量上传文件后，数据不需要做其他处理
可能这种场景比较少吧

**Comment by suyuan32** [comment]
> `field.JSON("images", []string{})` 确实还需要修改其它几个地方
> 
> ```
> 1、api：Images  []string `json:"images,optional"`
> 2、logic：SetNotNilImages(&req.Images)
> ```
> 
> 这样有个好处就是前端批量上传文件后，数据不需要做其他处理 可能这种场景比较少吧

json 字段自己手动处理下即可
